# Import packages

In [146]:
import numpy as np # numpy to generate random numbers
from scipy.optimize import minimize # scipy.optimize for the optimizer

# Set parameters and generate sample

In [147]:
mean = 5
st_dev = 5
sample_size = 100

In [148]:
sample = np.random.normal(mean,st_dev,sample_size)

In [149]:
sample

array([-0.31520083, -3.43949432,  5.78128436,  4.98808424,  5.3174978 ,
        8.58786284,  6.83308816, 11.35965481,  2.71635355,  1.48634011,
       12.1317345 ,  3.18980113,  0.20293359,  1.34336362,  3.77126379,
       -0.13926695,  5.66897302,  3.88640795,  4.6960748 ,  2.67227288,
        5.78172466,  5.41654914,  4.85459884,  7.94183508,  5.11019858,
       -2.04332329, -4.28047877,  2.640037  ,  0.23105784,  4.49472332,
        3.4213361 , 10.08754149,  6.78389355, 11.96634981,  2.03458619,
        8.01005477,  6.66015871,  5.10921952, 11.27465417,  6.50331507,
       -5.36424696,  7.42420913,  8.85878829, 11.08674874, 22.47051329,
       12.13010336, -0.3393019 , -2.33605566,  5.22026735,  2.96438392,
        3.2167891 ,  1.36753371,  4.38958129, -1.264782  ,  0.08850871,
       11.96459857,  3.19872267, -1.07471823, -1.29053509,  1.46662174,
        6.93130313,  6.44403961, -2.95523113,  5.95959685,  7.30631246,
        7.12664799,  6.0430929 ,  9.52340628,  3.89853568, -1.89

# Re-estimate parameters using Maximum Likelihood

In [150]:
def logLik(x):
    L = len(sample)*np.log(x[1]) + np.sum((sample-x[0])**2)/x[1]
    return L

In [151]:
print(logLik(np.array([5,7])))

527.496897773686


In [152]:
x0 = np.array([0,1]) # starting point for optimization

In [153]:
es = minimize(logLik, x0, method='nelder-mead', options={'xatol': 1e-8, 'disp': True})

Optimization terminated successfully.
         Current function value: 413.504725
         Iterations: 104
         Function evaluations: 207


In [154]:
es.final_simplex

(array([[ 4.43991988, 22.98972222],
        [ 4.43991988, 22.98972221],
        [ 4.43991988, 22.98972222]]),
 array([413.50472461, 413.50472461, 413.50472461]))